sudo: required
language: cpp

branches:
  except:
    - dev

notifications:
      email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt562
  - sudo apt-get update -q
  - sudo apt-cache search qt56
  - sudo apt-get install -qq g++-6 qt56-meta-minimal
  - curl https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz -o cmake-3.4.0-Linux-x86_64.tar.gz
  - tar xf cmake-3.4.0-Linux-x86_64.tar.gz
  - export PATH=$PWD/cmake-3.4.0-Linux-x86_64/bin/:$PATH
  - ls -lah /opt/
  - ls -lah /opt/qt56/
  - ls -lah /opt/qt56/bin/
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
  - travis/build.sh > /tmp/build_log.out 2>&1
after_failure:
  - cat /tmp/build_log.out
